apiVersion : apps/v1
kind: Deployment
metadata:
  name: semikalleldataeng 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semikalleldataeng
  template:
    metadata:
      labels:
        app: semikalleldataeng 
    spec:
      containers:
        - name: semikalleldataeng 
          image: uniqueacrregistrybackup.azurecr.io/semikalleldataeng
          ports:
          - containerPort: 80